### PR TITLE
fixing regression errors

### PR DESCRIPTION
**Pull request by erouvas**
#### What is this PR About?
Fixing regression as reported on https://github.com/redhat-cop/businessautomation-cop/issues/133

#### How do we test this?
https://github.com/redhat-cop/businessautomation-cop/issues/133 should be fixed

cc: @redhat-cop/businessautomation-cop

### CODE REVIEW

**Comment by garethahealy** [comment]
```
MacBook-Pro:pam-eap-setup garethhealy$ ./pam-setup.sh
macOS DETECTED
:: PROCEEDING WITH PAM771
:: PAM Installation mode : both
:: Installing EAP at /Users/garethhealy/Documents/github/redhat-cop/businessautomation-cop/pam-eap-setup/pam using jboss-eap-7.2.0.zip
:: Installing node1 as standalone_fb5ac9f4dac0
The batch executed successfully
process-state: reload-required
sed: 1: "/Users/garethhealy/Docu ...": extra characters at the end of g command
sed: 1: "/Users/garethhealy/Docu ...": extra characters at the end of g command
sed: 1: "/Users/garethhealy/Docu ...": extra characters at the end of g command
--- PAM771 Installation Summary ---

       PAM Installation mode : [ both ]
       Using Controller List : [ http://localhost:8080 ]
 Using Smart Router location : [ NOT INSTALLED ]
         Installed EAP using : [ jboss-eap-7.2.0.zip ]
        EAP install location : [ /Users/garethhealy/Documents/github/redhat-cop/businessautomation-cop/pam-eap-setup/pam ]
--- Node instalation node1 as standalone : standalone_fb5ac9f4dac0
         Installed PAM using : [ rhpam-7.7.1-business-central-eap7-deployable.zip ]
        Installed KIE SERVER : [ rhpam-7.7.1-kie-server-ee8.zip ]
        Added EAP admin user : [ admin / S3cr3tK3y# ]
              Added PAM user : [ pamAdmin / S3cr3tK3y# / kie-server,rest-all,admin,analyst,kiemgmt,manager,user,developer,process-admin ]
              Added PAM user : [ pamAnalyst / r3dh4t456^ / rest-all,analyst ]
              Added PAM user : [ pamDeveloper / r3dh4t456^ / rest-all,developer ]
              Added PAM user : [ pamUser / r3dh4t456^ / rest-all,user ]
              Added PAM user : [ kieServerUser / kieServerUser1234; / kie-server,rest-all ]
              Added PAM user : [ controllerUser / controllerUser1234; / kie-server,rest-all ]
              Startup script : [ go_pam.sh ]

./pam-setup.sh runtime :  24 secs.
```

this PRs output

**Comment by garethahealy** [comment]
The sed warnings are due to the default mac version not being GNU.

default mac:
```
MacBook-Pro:~ garethhealy$ sed --version
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

gnu sed via brew:
```
MacBook-Pro:pam-eap-setup garethhealy$ sed --version
sed (GNU sed) 4.8
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
Paolo Bonzini, Jim Meyering, and Assaf Gordon.

This sed program was built without SELinux support.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
```

**Comment by erouvas** [comment]
Does sed in mac support in place editing? That is option "-i".
For example, would the following return "faa" ?

echo "foo" > a; sed -i "s/oo/aa/" a; cat a

**Comment by erouvas** [comment]
Added checks on sed version for macOS

**Comment by garethahealy** [comment]
mac sed:
```
MacBook-Pro:pam-eap-setup garethhealy$ ./pam-setup.sh
macOS DETECTED
ERROR: GNU sed not found. Please install GNU sed.4.8 (or latest) to continue - Aborting
```

gnu sed:
```
MacBook-Pro:pam-eap-setup garethhealy$ ./pam-setup.sh
macOS DETECTED
:: PROCEEDING WITH PAM771
:: PAM Installation mode : both
:: Installing EAP at /Users/garethhealy/Documents/github/redhat-cop/businessautomation-cop/pam-eap-setup/pam using jboss-eap-7.2.0.zip
:: Installing node1 as standalone_9a51ed535bc0
The batch executed successfully
process-state: reload-required
--- PAM771 Installation Summary ---

       PAM Installation mode : [ both ]
       Using Controller List : [ http://localhost:8080 ]
 Using Smart Router location : [ NOT INSTALLED ]
         Installed EAP using : [ jboss-eap-7.2.0.zip ]
        EAP install location : [ /Users/garethhealy/Documents/github/redhat-cop/businessautomation-cop/pam-eap-setup/pam ]
--- Node instalation node1 as standalone : standalone_9a51ed535bc0
         Installed PAM using : [ rhpam-7.7.1-business-central-eap7-deployable.zip ]
        Installed KIE SERVER : [ rhpam-7.7.1-kie-server-ee8.zip ]
        Added EAP admin user : [ admin / S3cr3tK3y# ]
              Added PAM user : [ pamAdmin / S3cr3tK3y# / kie-server,rest-all,admin,analyst,kiemgmt,manager,user,developer,process-admin ]
              Added PAM user : [ pamAnalyst / r3dh4t456^ / rest-all,analyst ]
              Added PAM user : [ pamDeveloper / r3dh4t456^ / rest-all,developer ]
              Added PAM user : [ pamUser / r3dh4t456^ / rest-all,user ]
              Added PAM user : [ kieServerUser / kieServerUser1234; / kie-server,rest-all ]
              Added PAM user : [ controllerUser / controllerUser1234; / kie-server,rest-all ]
              Startup script : [ go_pam.sh ]

./pam-setup.sh runtime :  24 secs.
```

looks good to me

**Pull request merged**
