### PR TITLE
Revert "Renamed pam-example requests to replace : with _ due to windows clone issue"

### PR DESCRIPTION
**Pull request by ippul**
Reverts redhat-cop/businessautomation-cop#112

@garethahealy  @pamenon 
this file is use in all install.sh
it expect the file have the same name as the gav of the kjar to deploy

### CODE REVIEW

**Comment by garethahealy** [comment]
@ippul ; if this is reverted, you cant clone the repo on any windows machine... does it have to be the GAV?

**Comment by ippul** [comment]
> @ippul ; if this is reverted, you cant clone the repo on any windows machine... does it have to be the GAV?

No it can be modified but we have also to modify the install.sh to be "aware" of the new name

**Comment by ippul** [comment]
install script use this array declare -a kjars=("com.redhat.cop.pam:dmn-example5-kjar:1.0") for find the request.json to deploy the kjar

**Comment by garethahealy** [comment]
this line?
- https://github.com/redhat-cop/businessautomation-cop/blob/b551f0bdadcbb9f0eb6c6ba880d3b30430597e06/pam-quick-examples/dmn-example1/run.sh#L18

**Comment by ippul** [comment]
the lines are:    
DEPLOY="curl -s -u '$KIE_SERVER_USER:$KIE_SERVER_PASSWORD' -H 'accept: application/json' -H 'content-type: application/json' -X PUT '$KIE_SERVER_URL/containers/$1' -d@$EXAMPLE_PATH/requests/$1.json"
    UN_DEPLOY="curl -s -u '$KIE_SERVER_USER:$KIE_SERVER_PASSWORD' -H 'accept: application/json' -H 'content-type: application/json' -X DELETE '$KIE_SERVER_URL/containers/$1'"
    CHECK_IS_DEPLOY="curl -s -i -u '$KIE_SERVER_USER:$KIE_SERVER_PASSWORD' -H 'accept: application/json' -H 'content-type: application/json' -X GET '$KIE_SERVER_URL/containers/$1/release-id'"

**Comment by garethahealy** [comment]
OK, so we just need to update the $1 var, as per:

`$(echo "$1" | sed "s/:/_/g")`

**Comment by ippul** [comment]
Sounds good

**Comment by ippul** [comment]
I close this revert PR

**Pull request closed without merging**
